# Assignment: Data Wrangling
## `! git clone https://github.com/DS3001/wrangling`
## Do Q2, and one of Q1 or Q3.

**Q1.** Open the "tidy_data.pdf" document in the repo, which is a paper called Tidy Data by Hadley Wickham.

  1. Read the abstract. What is this paper about?
    *   The paper's main focus is about the data tidying component of data cleaning, as there is little research on how to make data cleaning efficient. The paper references a case study to demonstrate the advantages of the data tidying framework.
  2. Read the introduction. What is the "tidy data standard" intended to accomplish?
    *   The "tidy data standard" aims to provide a standard way to organize data values within a dataset by making intial data cleaning eaiser. It was designed with the goal of facilitating initial exploration and analysis of data, as well as simplify the development of data analysis tools that work well together.
  3. Read the intro to section 2. What does this sentence mean: "Like families, tidy datasets are all alike but every messy dataset is messy in its own way." What does this sentence mean: "For a given dataset, itâ€™s usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define variables and observations in general."
    *   The first sentence states that tidy datasets generally share the same properties and characteristics, whereas messy datasets have their own unique aspects. The second sentence implies that identifying what are observations and what are variabes tend to be intuitive, but when it comes to defining them, it could vary from person to person.
  4. Read Section 2.2. How does Wickham define values, variables, and observations?
    *   Wickham states that a dataset is a collection of values (numbers or strings) that can be organized in two ways. He states that every value belongs to a variable and an observation. A variable is defined as containing all values that measure the same underlying attribute across units. A observation is defined as containing all values measured on the same unit across attributes.
  5. How is "Tidy Data" defined in section 2.3?
    *   Tidy data is a standardized way of mapping the meaning of a dataset to its structure. A dataset can be classified as messy or tidy depending on how its rows, columns, and tables match up with observations, variables, and types. Characteristics of tidy data involve each variable forming a column, each observation forming a row, and each type of observational unit forming a table.
  6. Read the intro to Section 3 and Section 3.1. What are the 5 most common problems with messy datasets? Why are the data in Table 4 messy? What is "melting" a dataset?
    *   The 5 most common problems with messy data include: (1) column headers are values, not variable names; (2) multiple variables are stored in one column; (3) variables are stored in both rows and columns; (4) multiple types of observational units are stored in the same table; and (5) a single observational unit is stored in multiple tables. The data in Table 4 demonstrates a common type of messay dataset, which is tabular data designed for presentation. In this type of messy dataset, the variables form both rows and columns, and column headers are values rather than variable names. Melting a dataset involves turning columns into rows.
  7. Why, specifically, is table 11 messy but table 12 tidy and "molten"?
    *   Table 11 is considered messy because it has days along the top, which are values. Table 12 is considered tidy and molten because, compared to Table 11, it has taken those days and melted them into a single variable, "date". However, Table 12 isn't still completely tidy.
  8. Read Section 6. What is the "chicken-and-egg" problem with focusing on tidy data? What does Wickham hope happens in the future with further work on the subject of data wrangling?
    *   Wickham states that the "chick-end-egg" problem with tidy data is that if it is only as useful as the tools that work with it, then tidy tools will linked to tidy data. Overall, Wickham hopes that future work on the subject of data wrangling will build on the framework of data tidying to continue to develop ways that makes tasks related to cleaning data easier.

**Q2.** This question provides some practice cleaning variables which have common problems.
1. Numeric variable: For `./data/airbnb_hw.csv`, clean the `Price` variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)
2. Categorical variable: For the `./data/sharks.csv` data covered in the lecture, clean the "Type" variable as well as you can, and explain the choices you make.
3. Dummy variable: For the pretrial data covered in the lecture, clean the `WhetherDefendantWasReleasedPretrial` variable as well as you can, and, in particular, replace missing values with `np.nan`.
4. Missing values, not at random: For the pretrial data covered in the lecture, clean the `ImposedSentenceAllChargeInContactEvent` variable as well as you can, and explain the choices you make. (Hint: Look at the `SentenceTypeAllChargesAtConvictionInContactEvent` variable.)

In [ ]:
! git clone https://github.com/DS3001/wrangling

Cloning into 'wrangling'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 83 (delta 30), reused 15 (delta 10), pack-reused 41
Receiving objects: 100% (83/83), 10.85 MiB | 10.13 MiB/s, done.
Resolving deltas: 100% (36/36), done.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

**Question 2.1**

In [ ]:
df = pd.read_csv('./wrangling/assignment/data/airbnb_hw.csv', low_memory=False)
print( df.shape, '\n')
df.head()

(30478, 13)

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

In [ ]:
price = df['Price']
price.unique()
# By importing as a string, this allows us to later eliminate comma separators.

array(['145', '37', '28', '199', '549', '149', '250', '90', '270', '290',
       '170', '59', '49', '68', '285', '75', '100', '150', '700', '125',
       '175', '40', '89', '95', '99', '499', '120', '79', '110', '180',
       '143', '230', '350', '135', '85', '60', '70', '55', '44', '200',
       '165', '115', '74', '84', '129', '50', '185', '80', '190', '140',
       '45', '65', '225', '600', '109', '1,990', '73', '240', '72', '105',
       '155', '160', '42', '132', '117', '295', '280', '159', '107', '69',
       '239', '220', '399', '130', '375', '585', '275', '139', '260',
       '35', '133', '300', '289', '179', '98', '195', '29', '27', '39',
       '249', '192', '142', '169', '1,000', '131', '138', '113', '122',
       '329', '101', '475', '238', '272', '308', '126', '235', '315',
       '248', '128', '56', '207', '450', '215', '210', '385', '445',
       '136', '247', '118', '77', '76', '92', '198', '205', '299', '222',
       '245', '104', '153', '349', '114', '320', '292', '226', '420',
       '500', '325', '307', '78', '265', '108', '123', '189', '32', '58',
       '86', '219', '800', '335', '63', '229', '425', '67', '87', '1,200',
       '158', '650', '234', '310', '695', '400', '166', '119', '62',
       '168', '340', '479', '43', '395', '144', '52', '47', '529', '187',
       '209', '233', '82', '269', '163', '172', '305', '156', '550',
       '435', '137', '124', '48', '279', '330', '5,000', '134', '378',
       '97', '277', '64', '193', '147', '186', '264', '30', '3,000',
       '112', '94', '379', '57', '415', '236', '410', '214', '88', '66',
       '71', '171', '157', '545', '1,500', '83', '96', '1,800', '81',
       '188', '380', '255', '505', '54', '33', '174', '93', '740', '640',
       '1,300', '440', '599', '357', '1,239', '495', '127', '5,999',
       '178', '348', '152', '242', '183', '253', '750', '259', '365',
       '273', '197', '397', '103', '389', '355', '559', '38', '203',
       '999', '141', '162', '333', '698', '46', '360', '895', '10', '41',
       '206', '281', '449', '388', '212', '102', '201', '2,750', '4,750',
       '432', '675', '167', '390', '298', '339', '194', '302', '211',
       '595', '191', '53', '361', '480', '8,000', '4,500', '459', '997',
       '345', '216', '218', '111', '735', '276', '91', '490', '850',
       '398', '36', '775', '267', '625', '336', '2,500', '176', '725',
       '3,750', '469', '106', '460', '287', '575', '227', '263', '25',
       '228', '208', '177', '880', '148', '116', '685', '470', '217',
       '164', '61', '645', '699', '405', '252', '319', '268', '419',
       '343', '525', '311', '840', '154', '294', '950', '409', '184',
       '257', '204', '241', '2,000', '412', '121', '288', '196', '900',
       '647', '524', '1,750', '309', '510', '1,495', '1,700', '799',
       '383', '372', '492', '327', '1,999', '656', '224', '173', '875',
       '1,170', '795', '690', '146', '465', '1,100', '151', '274', '429',
       '825', '282', '256', '1,111', '620', '271', '161', '51', '855',
       '579', '1,174', '430', '20', '899', '649', '485', '181', '455',
       '4,000', '243', '342', '590', '560', '374', '437', '232', '359',
       '985', '31', '244', '254', '723', '237', '428', '370', '34',
       '1,400', '580', '2,520', '221', '749', '1,600', '2,695', '306',
       '202', '680', '570', '520', '223', '2,295', '213', '1,065', '346',
       '24', '286', '296', '266', '26', '995', '1,368', '393', '182',
       '635', '258', '780', '589', '347', '1,250', '1,350', '446',
       '3,200', '1,050', '1,650', '1,550', '975', '323', '6,500', '2,499',
       '1,850', '2,250', '715', '461', '540', '356', '439', '384', '569',
       '1,900', '22', '785', '626', '830', '318', '444', '321', '401',
       '1,499', '888', '369', '770', '386', '366', '344', '630', '313',
       '597', '262', '509', '10,000', '278', '312', '789', '1,195', '422',
       '21', '765', '3,500', '945', '326', '3,100', '2,486', '3,390',
       '1,356', '2,599', '472', '454', '328', '396', '291'], dtype=object)

In [ ]:
price = df['Price']
price = price.str.replace(',','') # replaces commas with nothing
print( price.unique() , '\n')
price = pd.to_numeric(price,errors='coerce') # typecast price to numeric
print( price.unique() , '\n')
print( 'Total missing: ', sum( price.isnull() ) ) # converting all the values

['145' '37' '28' '199' '549' '149' '250' '90' '270' '290' '170' '59' '49'
 '68' '285' '75' '100' '150' '700' '125' '175' '40' '89' '95' '99' '499'
 '120' '79' '110' '180' '143' '230' '350' '135' '85' '60' '70' '55' '44'
 '200' '165' '115' '74' '84' '129' '50' '185' '80' '190' '140' '45' '65'
 '225' '600' '109' '1990' '73' '240' '72' '105' '155' '160' '42' '132'
 '117' '295' '280' '159' '107' '69' '239' '220' '399' '130' '375' '585'
 '275' '139' '260' '35' '133' '300' '289' '179' '98' '195' '29' '27' '39'
 '249' '192' '142' '169' '1000' '131' '138' '113' '122' '329' '101' '475'
 '238' '272' '308' '126' '235' '315' '248' '128' '56' '207' '450' '215'
 '210' '385' '445' '136' '247' '118' '77' '76' '92' '198' '205' '299'
 '222' '245' '104' '153' '349' '114' '320' '292' '226' '420' '500' '325'
 '307' '78' '265' '108' '123' '189' '32' '58' '86' '219' '800' '335' '63'
 '229' '425' '67' '87' '1200' '158' '650' '234' '310' '695' '400' '166'
 '119' '62' '168' '340' '479' '43' '395' '144' '52' '47' '529' '187' '209'
 '233' '82' '269' '163' '172' '305' '156' '550' '435' '137' '124' '48'
 '279' '330' '5000' '134' '378' '97' '277' '64' '193' '147' '186' '264'
 '30' '3000' '112' '94' '379' '57' '415' '236' '410' '214' '88' '66' '71'
 '171' '157' '545' '1500' '83' '96' '1800' '81' '188' '380' '255' '505'
 '54' '33' '174' '93' '740' '640' '1300' '440' '599' '357' '1239' '495'
 '127' '5999' '178' '348' '152' '242' '183' '253' '750' '259' '365' '273'
 '197' '397' '103' '389' '355' '559' '38' '203' '999' '141' '162' '333'
 '698' '46' '360' '895' '10' '41' '206' '281' '449' '388' '212' '102'
 '201' '2750' '4750' '432' '675' '167' '390' '298' '339' '194' '302' '211'
 '595' '191' '53' '361' '480' '8000' '4500' '459' '997' '345' '216' '218'
 '111' '735' '276' '91' '490' '850' '398' '36' '775' '267' '625' '336'
 '2500' '176' '725' '3750' '469' '106' '460' '287' '575' '227' '263' '25'
 '228' '208' '177' '880' '148' '116' '685' '470' '217' '164' '61' '645'
 '699' '405' '252' '319' '268' '419' '343' '525' '311' '840' '154' '294'
 '950' '409' '184' '257' '204' '241' '2000' '412' '121' '288' '196' '900'
 '647' '524' '1750' '309' '510' '1495' '1700' '799' '383' '372' '492'
 '327' '1999' '656' '224' '173' '875' '1170' '795' '690' '146' '465'
 '1100' '151' '274' '429' '825' '282' '256' '1111' '620' '271' '161' '51'
 '855' '579' '1174' '430' '20' '899' '649' '485' '181' '455' '4000' '243'
 '342' '590' '560' '374' '437' '232' '359' '985' '31' '244' '254' '723'
 '237' '428' '370' '34' '1400' '580' '2520' '221' '749' '1600' '2695'
 '306' '202' '680' '570' '520' '223' '2295' '213' '1065' '346' '24' '286'
 '296' '266' '26' '995' '1368' '393' '182' '635' '258' '780' '589' '347'
 '1250' '1350' '446' '3200' '1050' '1650' '1550' '975' '323' '6500' '2499'
 '1850' '2250' '715' '461' '540' '356' '439' '384' '569' '1900' '22' '785'
 '626' '830' '318' '444' '321' '401' '1499' '888' '369' '770' '386' '366'
 '344' '630' '313' '597' '262' '509' '10000' '278' '312' '789' '1195'
 '422' '21' '765' '3500' '945' '326' '3100' '2486' '3390' '1356' '2599'
 '472' '454' '328' '396' '291']

[  145    37    28   199   549   149   250    90   270   290   170    59
    49    68   285    75   100   150   700   125   175    40    89    95
    99   499   120    79   110   180   143   230   350   135    85    60
    70    55    44   200   165   115    74    84   129    50   185    80
   190   140    45    65   225   600   109  1990    73   240    72   105
   155   160    42   132   117   295   280   159   107    69   239   220
   399   130   375   585   275   139   260    35   133   300   289   179
    98   195    29    27    39   249   192   142   169  1000   131   138
   113   122   329   101   475   238   272   308   126   235   315   248
   128    56   207   450   215   210   385   445   136   247   118    77
    76    92   198   205   299   222   245   104   153   349   114   320
   292   226   420   500   325   307    78   265   108   123   189    32
    58    86   219   800   335    63   229   425    67    87  1200   158
   650   234   310   695   400   166   119    62   168   340   479    43
   395   144    52    47   529   187   209   233    82   269   163   172
   305   156   550   435   137   124    48   279   330  5000   134   378
    97   277    64   193   147   186   264    30  3000   112    94   379
    57   415   236   410   214    88    66    71   171   157   545  1500
    83    96  1800    81   188   380   255   505    54    33   174    93
   740   640  1300   440   599   357  1239   495   127  5999   178   348
   152   242   183   253   750   259   365   273   197   397   103   389
   355   559    38   203   999   141   162   333   698    46   360   895
    10    41   206   281   449   388   212   102   201  2750  4750   432
   675   167   390   298   339   194   302   211   595   191    53   361
   480  8000  4500   459   997   345   216   218   111   735   276    91
   490   850   398    36   775   267   625   336  2500   176   725  3750
   469   106   460   287   575   227   263    25   228   208   177   880
   148   116   685   470   217   164    61   645   699   405   252   319
   268   419   343   525   311   840   154   294   950   409   184   257
   204   241  2000   412   121   288   196   900   647   524  1750   309
   510  1495  1700   799   383   372   492   327  1999   656   224   173
   875  1170   795   690   146   465  1100   151   274   429   825   282
   256  1111   620   271   161    51   855   579  1174   430    20   899
   649   485   181   455  4000   243   342   590   560   374   437   232
   359   985    31   244   254   723   237   428   370    34  1400   580
  2520   221   749  1600  2695   306   202   680   570   520   223  2295
   213  1065   346    24   286   296   266    26   995  1368   393   182
   635   258   780   589   347  1250  1350   446  3200  1050  1650  1550
   975   323  6500  2499  1850  2250   715   461   540   356   439   384
   569  1900    22   785   626   830   318   444   321   401  1499   888
   369   770   386   366   344   630   313   597   262   509 10000   278
   312   789  1195   422    21   765  3500   945   326  3100  2486  3390
  1356  2599   472   454   328   396   291]

Total missing:  0

**Question 2.2**

In [ ]:
df = pd.read_csv('./wrangling/assignment/data/sharks.csv', low_memory=False)
# df.head()
# df.columns.tolist()

In [ ]:
df['Type'].value_counts()

Unprovoked             4716
Provoked                593
Invalid                 552
Sea Disaster            239
Watercraft              142
Boat                    109
Boating                  92
Questionable             10
Unconfirmed               1
Unverified                1
Under investigation       1
Boatomg                   1
Name: Type, dtype: int64

In [ ]:
type = df['Type'] # creates a temporary vector of values for the Type variable

type = type.replace(['Sea Disaster', 'Boat','Boating','Boatomg'],'Watercraft') # watercraft/boating values
type.value_counts()

type = type.replace(['Invalid', 'Questionable','Unconfirmed','Unverified','Under investigation'],np.nan) # unclean values
type.value_counts()

df['Type'] = type # replacing the 'Type' variable with the cleaned version
del type # destroys the temporary vector

df['Type'].value_counts()

Unprovoked    4716
Provoked       593
Watercraft     583
Name: Type, dtype: int64

In [ ]:
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].replace(['UNKNOWN', 'F','M','2017'],np.nan) # unclean values
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].replace('y','Y') # unclean values
pd.crosstab(df['Type'],df['Fatal (Y/N)'],normalize='index')

Fatal (Y/N)         N         Y
Type
Provoked     0.967521  0.032479
Unprovoked   0.743871  0.256129
Watercraft   0.684303  0.315697

**Question 2.3**

In [ ]:
df = pd.read_parquet('./wrangling/data/justice_data.parquet')
# df.head()
# df.columns.tolist()

In [ ]:
release = df['WhetherDefendantWasReleasedPretrial']
print(release.unique(),'\n')
print(release.value_counts(),'\n')
release = release.replace(9,np.nan) # the 9's are "unclear" according to codebook
print(release.value_counts(),'\n')
sum(release.isnull()) # 31 missing values
df['WhetherDefendantWasReleasedPretrial'] = release # replacing data column with cleaned values
del release

[nan  0.  1.]

1.0    19154
0.0     3801
Name: WhetherDefendantWasReleasedPretrial, dtype: int64

1.0    19154
0.0     3801
Name: WhetherDefendantWasReleasedPretrial, dtype: int64

**Question 2.4**

In [ ]:
length = df['ImposedSentenceAllChargeInContactEvent']
type = df['SentenceTypeAllChargesAtConvictionInContactEvent']

# print( length.unique()  , '\n') # values that are ' ' denote missing
length = pd.to_numeric(length,errors='coerce') # coerce to numeric
length_NA = length.isnull() # creating a missing dummy
print( np.sum(length_NA),'\n') # 9k missing values of 23k

print( pd.crosstab(length_NA, type), '\n') # Category 4 is cases where the charges were dismissed

length = length.mask( type == 4, 0) # replacing length with 0 when type ==4
length = length.mask( type == 9, np.nan) # replacing length with np.nan when type == 9

length_NA = length.isnull() # creating a new missing dummy
print( pd.crosstab(length_NA, type), '\n')
print( np.sum(length_NA),'\n') # 274 missing

df['ImposedSentenceAllChargeInContactEvent'] = length # replacing data with cleaned version
del length, type # deleting temporary length/type variables

9053

SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914     0    0
True                                                 0     0    0  8779  274

SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914  8779    0
True                                                 0     0    0     0  274

274